#zoonet_ypus_homepage:
#    pattern:  /hello/{name}
#    defaults: { _controller: ZoonetYpusBundle:Default:index }
ZoonetYpusBundle_homepage:
    pattern:  /
    defaults: { _controller: ZoonetYpusBundle:Page:index }
    requirements:
        _method:  GET
