parameters:
#    zoonet_ypus.example.class: Zoonet\YpusBundle\Example

services:
#    zoonet_ypus.example:
#        class: %zoonet_ypus.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
